apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: node-test
  labels:
    app: node-test
spec:
  selector:
    matchLabels:
      app: node-test
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: node-test
        tier: node-test
    spec:
      containers:
      - name: node-test
        image: gcr.io/crowde-apps-258709/jenkins_node_example:master-VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: node-test

---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: node-test
  labels:
    app: node-test
spec:
  ports:
    - port: 5000
      targetPort: 8081
  selector:
    app: node-test
    tier: node-test
  type: LoadBalancer